### ISSUE TITLE
New SubQuery project that can index blocks, transactions, and state-update events

### ISSUE THREAD

**Issue by toliaqat** [Agoric/dapp-inter#228]
```[tasklist]
### Tasks
- [x] OCap parsing for vaults and oracle_price state events
- [x] GraphQL API exposing vaults, and oracle_prices data
- [x] Productionize the API keys for deployment on Managed SubQuery
- [x] Deploy project on SubQuery managed service
- [ ] Verify data is indexed
```
